live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "ubuntu"
args = [""]

[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 1.0
blur = false
dynamic_padding = true
padding = { x = 8, y = 8 }

[window.dimensions]
columns = 144
lines = 32

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "EaseOutExpo"
color = "0xfab795"
duration = 4

[cursor]
style = "Block"
unfocused_hollow = true

# ======================
# Font Configuration
# ======================
[font]
size = 12
offset = { x = 0, y = 2 }

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Regular Italic"

# ======================
# Color Scheme
# ======================
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.cursor]
cursor = "0x29d398"

[colors.normal]
black = "0x16161e"
blue = "0x2bc3de"
cyan = "0x62e0e2"
green = "0x2ed8a2"
magenta = "0xd1aff8"
red = "0xec6183"
white = "0xe2e2e2"
yellow = "0xe8b195"

[colors.primary]
background = "0x1C1E26"
foreground = "0xe0e0e0"

# ======================
# Mouse Settings
# ======================
[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# ======================
# Key Bindings
# ======================
[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001w"
key = "S"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001q"
key = "D"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001k"
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001j"
key = "K"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"
