# Configuration for Alacritty, the GPU enhanced terminal emulator
# Documentation: https://posts.michaelks.org/simulating-macos-terminal-bindings-in-alacritty/

window:
  # Window dimensions (changes require restart)
  dimensions:
    columns: 130
    lines: 45

  # Window padding (changes require restart)
  padding:
    x: 5
    y: 5

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window decorations
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations: buttonless

  # Startup Mode (changes require restart)
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  startup_mode: Windowed

  # Window opacity
  opacity: 1.0
  
scrolling:
  # maximum number of lines in the scrollback buffer. Specifying '0' will
  # disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: "FiraCode Nerd Font Mono"
    style: Light

  # The bold font face
  bold:
    family: "FiraCode Nerd Font Mono"
    style: Medium

  # The italic font face
  italic:
    family: "FiraCode Nerd Font Mono"
    style: "Light Italic"

  # Point size of the font
  size: 15.5

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0


# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

# Colors (Horizon Dark - https://github.com/eendroroy/alacritty-theme/blob/master/themes/horizon-dark.yaml)
colors:
  # Primary colors
  primary:
    background: "0x1e212b"
    foreground: "0xe0e0e0"

  # Cursor color
  cursor:
    cursor: '0x29d398'
    
  # Normal colors
  normal:
    black: "0x16161c"
    red: "0xe95678"
    green: "0x29d398"
    yellow: "0xfab795"
    blue: "0x26bbd9"
    magenta: "0xee64ac"
    cyan: "0x59e1e3"
    white: "0xd5d8da"

  # Bright colors
  bright:
    black: "0x5b5858"
    red: "0xec6a88"
    green: "0x3fdaa4"
    yellow: "0xfbc3a7"
    blue: "0x3fc4de"
    magenta: "0xf075b5"
    cyan: "0x6be4e6"
    white: "0xd5d8da"

# Visual Bell
bell:
  animation: EaseOutExpo
  color: "0xfab795"
  duration: 4

# Key bindings (Read key code with `xxd -psd`)
key_bindings:
  - { key: Q, mods: Command, action: Quit } # Quit Alacritty
  - { key: M, mods: Command, action: Minimize } # Minimize Alacritty

  - { key: T, mods: Command, chars: "\x01\x63" } # Open New Tab
  - { key: S, mods: Command, chars: "\x01\x77" } # Select Tab
  - { key: D, mods: Command, chars: "\x01\x71" } # Select Screen
  - { key: W, mods: Command, chars: "\x01\x78" } # Close Screen

  - { key: Key1, mods: Command, chars: "\x01\x31" } # Switch To Tab 1
  - { key: Key2, mods: Command, chars: "\x01\x32" } # Switch To Tab 2
  - { key: Key3, mods: Command, chars: "\x01\x33" } # Switch To Tab 3
  - { key: Key4, mods: Command, chars: "\x01\x34" } # Switch To Tab 4
  - { key: Key5, mods: Command, chars: "\x01\x35" } # Switch To Tab 5
  - { key: Key6, mods: Command, chars: "\x01\x36" } # Switch To Tab 6
  - { key: Key7, mods: Command, chars: "\x01\x37" } # Switch To Tab 7
  - { key: Key8, mods: Command, chars: "\x01\x38" } # Switch To Tab 8
  - { key: Key9, mods: Command, chars: "\x01\x39" } # Switch To Tab 9

  - { key: J, mods: Command, chars: "\x01\x6b" } # Split Vertical
  - { key: K, mods: Command, chars: "\x01\x6a" } # Split Horizontal

  - { key: Back, mods: Command, chars: "\x15" } # Delete Line

  - { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }
  - { key: Key0,           mods: Control,                         action: ResetFontSize    }
  
mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  # URL launcher
  #modifiers: Control|Shift
  hints:
    launcher:
      program: open # This depends on your OS, on Mac it’s `open`
    modifiers: Command

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Mouse bindings
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# dynamic_title: true

# Live config reload (changes require restart)
live_config_reload: true

debug:
  # Should display the render timer
  render_timer: false

  # Keep the log file after quitting Alacritty.
  persistent_logging: false

  # Log level
  log_level: Off

  # Print all received window events.
  print_events: false

# Startup directory
#
# Directory the shell is started in. If this is unset, or `None`, the working
# directory of the parent process will be used.
# working_directory: ~/Projects

# Shell
# Start fish with tmux session
shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main

# Support 256 color
env:
  TERM: xterm-256color